#端口号
server:
  port: 8001

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java4
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/pad/mapper/xml/*.xml
  #开启日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.pad.entity
